# fly.toml app configuration file generated for grab-market-server-test-0013 on 2023-12-16T15:22:06+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grab-market-server-test-0013"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
